dist: bionic
language:
  - cpp
  - python
compiler: gcc
python: "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-7
      - python3.6-dev

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.0.0/bazel_1.0.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.0.0-linux-x86_64.deb

script:
  - tools/buildall.sh
